### ISSUE TITLE
I feel like there should be a d2 and a d3 dice in `roll()`

### ISSUE THREAD

**Issue by wadedismukes** [njlyon0/dndR#10]

**Comment by njlyon0** [comment]
Hm, "d2" is an accepted argument of `roll` already but what would you use a d3 for?

Also, I've considered just allowing any number of dice sides including weird dice (e.g., `d17`, etc.), do you think that would be helpful or should it be left as a discrete set of allowed dice?

**Comment by wadedismukes** [comment]
I run into "roll a d3" on a table in a book. I do not think all dice sides should be allowed (no one is rolling d17).

**Comment by njlyon0** [comment]
`roll` will now accept any number of three-sided dice (i.e., "_d3" where the "_" is a number up to 10,000,000)! I've also added a `show_dice` argument to the `roll` function. If set to `TRUE` (defaults to `FALSE`) it will message all of the individual rolls included in the total value.

I've updated the `pkgdown` site, `NEWS.md` and the README with these tweaks and everything looks functional on my end. Ping me if you have issues but otherwise I'm marking this as complete 😄
